spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    hikari:
      username: root
      password: 951209
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    # host: 112.124.24.139
    database: 0
    timeout: 1000
    password:

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
server:
  port: 8888

mybatis-plus:
  global-config:
    # 关闭banner
    banner: false
logging:
  level:
    com:
      usts:
        salarymanage:
          mapper: debug
pagehelper:
  reasonable: true